// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBggxmRaIfF78q1bFPbNeFga33Ca_rwu1s',
    appId: '1:233182185988:web:bc06331cef56ee24604351',
    messagingSenderId: '233182185988',
    projectId: 'point-plus-4a006',
    authDomain: 'point-plus-4a006.firebaseapp.com',
    storageBucket: 'point-plus-4a006.firebasestorage.app',
    measurementId: 'G-5WWPD1J2MF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCdQ5d1UzTsLjfUhhf2XCTiqKs9xG3JVBI',
    appId: '1:233182185988:android:68e113e6aebfadaf604351',
    messagingSenderId: '233182185988',
    projectId: 'point-plus-4a006',
    storageBucket: 'point-plus-4a006.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCa9YUmt4kE_Wh8lTs4GRDV67Mu_aPGJGo',
    appId: '1:233182185988:ios:4d6698aab977dab5604351',
    messagingSenderId: '233182185988',
    projectId: 'point-plus-4a006',
    storageBucket: 'point-plus-4a006.firebasestorage.app',
    iosBundleId: 'app.digitalbase.merchant',
  );

}